name: 自动构建发布
on: push

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v3
      - name: 设置版本号
        run: echo "PACK_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - name: 设置插件名
        run: echo "PACK_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
      - name: 安装 PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
      - name: 安装 Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version: lts/*
          cache: pnpm
      - name: 安装依赖
        run: pnpm i
      - name: 构建项目
        run: pnpm build
      - name: 上传产物到 Action Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ env.PACK_NAME }}-${{ env.PACK_VERSION }}
          path: dist/*